# Generated by Django 4.1.1 on 2024-03-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DisasterID', '0007_userprofile_password'),
        ('userProfile', '0002_shelterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Bungalow', 'Bungalow'), ('Cottage', 'Cottage'), ('Other', 'Other')], max_length=100)),
                ('room_numbers', models.IntegerField()),
                ('availability_of_toilets', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('drinking_water_source', models.BooleanField(choices=[(True, 'Available'), (False, 'Not available')])),
                ('ownership_type', models.CharField(choices=[('Self Owned', 'Self Owned'), ('Govt. Owned', 'Govt. Owned'), ('Rented', 'Rented')], max_length=50)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DisasterID.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='ShelterDetails',
        ),
    ]
