# Generated by Django 5.0.1 on 2024-02-03 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisasterID', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuserdetails',
            name='username',
        ),
        migrations.AddField(
            model_name='basicuserdetails',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='basicuserdetails',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basicuserdetails',
            name='livelihood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='basicuserdetails',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
