# Generated by Django 5.0.1 on 2024-02-03 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisasterID', '0002_remove_basicuserdetails_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='gramPanchayat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='longitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='tehsil_or_block',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='ward_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='basicuserdetails',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
