# Generated by Django 5.0.1 on 2024-02-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisasterID', '0004_userprofile_disaster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='disaster_id',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
