# Generated by Django 5.0.1 on 2024-02-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisasterID', '0006_useraddress_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
